# Generated by Django 3.1 on 2020-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
