# Generated by Django 3.1 on 2020-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_items_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='rate',
            field=models.FloatField(default=None, null=True),
        ),
    ]
